export const saleItems = [
  {
    id: 1,
    name: "Áo thun unisex",
    sale: -14,
    src: "/img/sale1.png",
    sale_price: "150.000",
    sold: "500",
  },
  {
    id: 2,
    name: "Váy trắng oversize nữ",
    sale: -22,
    src: "/img/sale2.png",
    sale_price: "250.000",
    sold: "350",
  },
  {
    id: 3,
    name: "Quạt điện cầm tay",
    sale: -40,
    src: "/img/sale3.png",
    sale_price: "370.000",
    sold: "1k2",
  },
  {
    id: 4,
    name: "Quần ống rộng cho nữ",
    sale: -24,
    src: "/img/sale4.png",
    sale_price: "230.000",
    sold: "180",
  },
  {
    id: 5,
    name: "Chiếu tre",
    sale: -30,
    src: "/img/sale5.png",
    sale_price: "160.000",
    sold: "590",
  },
  {
    id: 6,
    name: "Ô cao cấp chống thấm tốt",
    sale: -25,
    src: "/img/sale6.png",
    sale_price: "140.000",
    sold: "1k8",
  },
  {
    id: 7,
    name: "Nước giặt Omo ",
    sale: -18,
    src: "/img/sale7.png",
    sale_price: "150.000",
    sold: "3k",
  },
  {
    id: 8,
    name: "Áo ngực không gọng gọn nhẹ ",
    sale: -35,
    src: "/img/sale8.png",
    sale_price: "136.000",
    sold: "800",
  },
  {
    id: 9,
    name: "Áo thun polo nam tay ngắn",
    sale: -27,
    src: "/img/sale9.png",
    sale_price: "190.000",
    sold: "1k1",
  },
  {
    id: 10,
    name: "Dầu gội thảo dược nguyên xuân",
    sale: -45,
    src: "/img/sale10.png",
    sale_price: "109.000",
    sold: "5k",
  },
  {
    id: 11,
    name: "Xịt thơm phòng Dove vị chanh",
    sale: -34,
    src: "/img/sale11.png",
    sale_price: "110.000",
    sold: "3k8",
  },
  {
    id: 12,
    name: "Son kem lì mịn môi Romand",
    sale: -29,
    src: "/img/sale12.png",
    sale_price: "170.000",
    sold: "520",
  },
];
